### ISSUE TITLE
Write meta terminal commands

### ISSUE THREAD

**Issue by ecfidler** [benrucker/whid-site-nuxt#273]
- describe how the scoring worked? including the initial method and how it was changed to be wackier after a few weeks while ben was drunk? (cheeto cheeto)
- include how scores loop around from 1600
- at 7am on april 1st Ethan and Ben met up to make sure that it worked, and it didnt so we needed to manually activate it.
- creation of Dennis
- CUMPEG
- format all of these like they are chat logs between Ben and Ethan?
- have some corrupted / jumbled text
- folder title: subpoena documents, backups,

**Comment by benrucker** [comment]
this specifically references the real/fake conversations between us about
the creation of whyd22/the terminal
