### ISSUE TITLE
Author avatar bubble should have a transition on it

### ISSUE THREAD

**Issue by benrucker** [benrucker/whid-site-nuxt#86]
Best fix: have it slide down to the next message
Quick fix: have it fade in and out

**Comment by benrucker** [comment]
https://github.com/benrucker/whid-site-nuxt/commit/7fb113eea11e37495d5978c4bed67a151c58d242 - now it should be easy to transition the `opacity` attribute

**Comment by ecfidler** [comment]
add vue transition-in moving down to center, and add vue transition-out moving to bottom

**Comment by benrucker** [comment]
done with a8642f3ba17df659abda628ea966e5566d2c38b5 and d05160e960cf71892dcf316d158d2cf2bea36618 + f7ba49e0417fdbf7404af55a4de09210684a1d41
